# Generated by Django 4.1.6 on 2023-02-12 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("factory", "0002_measure_measure_name_alter_measure_author_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="measure",
            options={"verbose_name": "измерение", "verbose_name_plural": "измерения"},
        ),
        migrations.AlterModelOptions(
            name="project",
            options={"verbose_name": "проект", "verbose_name_plural": "проекты"},
        ),
        migrations.AlterField(
            model_name="measure",
            name="data",
            field=models.FileField(upload_to=""),
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
