# Generated by Django 3.2.18 on 2023-02-18 12:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('factory', '0005_alter_measure_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='processed_data',
            field=models.FileField(default=django.utils.timezone.now, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
