# Generated by Django 3.2.18 on 2023-02-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("factory", "0006_measure_processed_data"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="is_monitored",
            field=models.BooleanField(default=False),
        ),
    ]
